version: '3.3'
services:
    mongo:
        image: mongo
        container_name: mongo-database
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: passwordRoot
          MONGO_INITDB_DATABASE: laravel-dev
          MONGODB_DATABASE: laravel-dev
        volumes:
          - ./mongosetup.js:/docker-entrypoint-initdb.d/mongosetup.js
        networks:
          custom_network:
            ipv4_address: 172.100.0.3
    mongo-express:
        image: mongo-express
        container_name: mongo-express-interface
        ports:
          - 8082:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: passwordRoot
          ME_CONFIG_OPTIONS_EDITORTHEME: ambiance 
          ME_CONFIG_MONGODB_SERVER: 172.100.0.3
          ME_CONFIG_MONGODB_PORT: 27017
          ME_CONFIG_BASICAUTH_USERNAME: root
          ME_CONFIG_BASICAUTH_PASSWORD: passwordRoot
        depends_on: 
          - mongo
        networks:
          custom_network:
            ipv4_address: 172.100.0.5
    php-apache:
        container_name: "app-Laravel"
        build: .
        #command: "composer install"
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
        networks: 
            custom_network:
                ipv4_address: 172.100.0.4    
networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/24